stages:
  - build-docker-image
  - run-linter
  - run-type-checking
  - run-tests

build-docker-image:
  stage: build-docker-image
  image: docker:18.09.7

  services:
    - docker:dind
 
  variables:
    DOCKER_DRIVER: overlay2

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

run-linter:
  variables:
    GIT_STRATEGY: none
  stage: run-linter
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    entrypoint: [""]

  script:
    - pwd
    - cd /app
    - ls
    - rake standard

run-type-checking:
  variables:
    GIT_STRATEGY: none
  stage: run-type-checking
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    entrypoint: [""]

  script:
    - srb tc

run-tests:
  variables:
    GIT_STRATEGY: none
  stage: run-tests
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    entrypoint: [""]

  services:
    - name: postgres:12
      alias: db

  script:
    - RAILS_ENV=test rails db:create
    - RAILS_ENV=test rails db:schema:load
    - rails test