version: '3.7'
services:
  db:
    image: postgres:12
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password1234
    
  web:
    build: .
    # Run the container via RubyMine.
    #command: tail -f /dev/null
    # Run the compose outside RubyMine.
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
      - yarn-volume:/usr/local/node_modules
    ports:
      - "3000:3000"
      - "1234:1234" # RubyMine
    depends_on:
      - db

volumes:
  bundle-volume:
  yarn-volume:
  db-volume:
