name: CI
on: [push]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image Step
        run: docker-compose build web

      - name: Rubocop Standard
        run: docker-compose run web rake standard

      - name: Run Sorbet
        run: docker-compose run web srb tc

      - name: Test setup
        run: |
          docker-compose run web RAILS_ENV=test bundle exec rails db:create
          docker-compose run web RAILS_ENV=test bundle exec rails db:schema:load

      - name: Run tests
        run: docker-compose run web bundle exec rails test
